version: "3"

services:
  go-admin-web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: go-admin-web
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

